# Generated by Django 3.0.8 on 2020-08-05 20:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_auto_20200722_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=str)),
                ('email', models.TextField(default=str)),
                ('orcid', models.TextField(default=str)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Author', 'Author'), ('Conceptualization', 'Conceptualization'), ('ContactPerson', 'Contactperson'), ('DataCollector', 'Datacollector'), ('DataCurator', 'Datacurator'), ('DataManager', 'Datamanager'), ('FormalAnalysis', 'Formalanalysis'), ('FundingAcquisition', 'Fundingacquisition'), ('Investigation', 'Investigation'), ('Maintainer', 'Maintainer'), ('Methodology', 'Methodology'), ('Producer', 'Producer'), ('ProjectLeader', 'Projectleader'), ('ProjectManager', 'Projectmanager'), ('ProjectMember', 'Projectmember'), ('ProjectAdministration', 'Projectadministration'), ('Researcher', 'Researcher'), ('Resources', 'Resources'), ('Software', 'Software'), ('Supervision', 'Supervision'), ('Validation', 'Validation'), ('Visualization', 'Visualization'), ('Funder', 'Funder'), ('Sponsor', 'Sponsor'), ('StudyParticipant', 'Studyparticipant'), ('Other', 'Other')], default='Other', max_length=21), default=list, size=None)),
                ('affiliations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=str), default=list, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='version',
            name='contributors',
            field=models.ManyToManyField(to='publish.Contributor'),
        ),
    ]
