# Generated by Django 3.0.8 on 2020-08-07 20:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_auto_20200722_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(blank=True, max_length=65536)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('url', models.TextField(blank=True, max_length=65536)),
                ('includeInCitation', models.BooleanField(blank=True)),
                ('awardNumber', models.TextField(blank=True, max_length=65536)),
                ('contributorType', models.CharField(max_length=12)),
                ('affiliation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('contactPoint', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('roleName', models.ManyToManyField(to='publish.Role')),
            ],
        ),
        migrations.AddField(
            model_name='version',
            name='contributors',
            field=models.ManyToManyField(to='publish.Contributor'),
        ),
    ]
