# Generated by Django 3.0.5 on 2020-05-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_auto_20200512_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nwbfile',
            name='dandiset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.Dandiset'),
        ),
    ]
